### ISSUE TITLE
Can't disable `min_java` version validation

### ISSUE THREAD

**Issue by ykrasik** [keastrid/Why#3]
Hi,

Thanks for this library.

I ran into an issue when bundling a Java app using [JavaPackager](https://github.com/fvarrui/JavaPackager).
In my Gradle script I'm specifying the `JavaPackager.jrePath` as `jrePath = new File(System.properties['java.home'])`. I'm bundling the app with the JRE that comes with the JDK. However, the `release` file of my JDK (1.8) is not located inside the `jre` folder which gets bundled, but it sits as a child of the `jdk` folder - see below.

```
jdk1.8.0_271
|-> release
|-> jre    <- this is what gets bundled
    |-> no release file
```

This causes the bundled jre to be considered incompatible by [this code](https://github.com/AstroImageJ/Why/blob/0e40cf2cf58363f17ab31b3f31aa2e5abfacc31e/src/file_handler.rs#L206).

Currently, there is no way to completely disable this version validation, as even setting the `min_java` to 0 or leaving it unset causes the validation to run (and fail). For the case of bundling a JRE, this validation should be turned off.

**Comment by keastrid** [comment]
I've pushed a potential fix, please give it a try.

`check_main_class` must be disabled, and the jre path must point to a valid `jvm.dll`.

**Comment by ykrasik** [comment]
Thanks! I'm not running this directly, but through [JavaPackager](https://github.com/fvarrui/JavaPackager). I'll wait for a new version of JavaPackager to be released and let you know.

**Comment by ykrasik** [comment]
Tested it, it works for me.
I think the author of JavaPackager is waiting for a new officially released version of Why in order to incorporate it into the next version of JavaPackager (See the [issue](https://github.com/fvarrui/JavaPackager/issues/250#issuecomment-1245303674))

P.S.
There's a small optimization that can be done where the [compatible_java_version](https://github.com/AstroImageJ/Why/blob/58f1de23cbd214f64e44f0ab6e25a9283cb1d4ca/src/file_handler.rs#L117) check can be skipped completely if `min_java_ver` == 0, since `compatible_java_version` does a few file system access operations skipping it may save a few milliseconds.

**Comment by keastrid** [comment]
1.1.2 released. Thanks for the issue report!

There are probably some optimizations to be made, but I'd rather not touch the path finding part as its difficult to test - there were some incomprehensible JVM crashes due to how Windows loads DLLs.
